version: '3.7'
services:
    wordpress:
        image: wordpress:latest
        restart: "on-failure"
        networks:
            - wp_bl_default
        volumes: 
            - /var/www/html
            - ./content/themes:/var/www/html/wp-content/themes/
            - ./content/plugins:/var/www/html/wp-content/plugins/
            - ./wp_php_conf/php.ini:/usr/local/etc/php/conf.d/php.ini
        labels: 
            - "traefik.enable=true"
            - "traefik.http.routers.wpBPsite.rule=Host(`${SITEURL:?err}`, `www.${SITEURL:?err}`)"
            - "traefik.http.routers.wpBPsite.entrypoints=web"
            - "traefik.docker.network=wp_bl_default"
        expose: 
            - '80'
        ports:
            - "80"
        environment: 
            - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
            - WORDPRESS_DB_USER=${DB_USER_NAME:-wordpress}
            - WORDPRESS_DB_PASSWORD=${DB_USER_PASS:-wordpress}
            - WORDPRESS_DB_HOST=db:3306
            - PHP_VERSION=7.4.9
    mysql_db:
        image: mysql:5.7
        restart: "on-failure"
        expose: 
            - '3306'
        
        environment: 
            - MYSQL_DATABASE=${DB_NAME:-wordpress}
            - MYSQL_USER=${DB_USER_NAME:-wordpress}
            - MYSQL_PASSWORD=${DB_USER_PASS:-wordpress}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-root}
        networks:
            wp_bl_default:
                aliases:
                    - db
        volumes: 
            - db_data:/var/lib/mysql
    traefik:
        image: "traefik:v2.2"
        restart: "on-failure"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            wp_bl_default:

networks:
    wp_bl_default:
        driver: bridge
volumes:
    db_data:
